### ISSUE TITLE
Missing some dependencies and url encoding issue

### ISSUE THREAD

**Issue by achengli** [THEGOLDENPRO/aghpb.lua#1]
Hello,

I did a modification to allow search topics as c++ using **urlencode** package available on **Luarocks**.

I hope you find it useful.

**Comment by THEGOLDENPRO** [comment]
Thank you so much for this, I really appreciate it. 
It's my first time using Lua so I didn't know how url encoding was done correctly.

Thanks 💙

**Comment by THEGOLDENPRO** [comment]
merged 👍
