### ISSUE TITLE
The package couldn't be downloaded via luarocks

### ISSUE THREAD

**Issue by achengli** [THEGOLDENPRO/aghpb.lua#3]
Hello **Jassim**,

Sorry for not saw it before, I have seen that the package can not be installed because the download information is written wrong in the **rockspec** file. 

I did another modification to follow better the standards moving the main code file inside a sub-directory inside **src** directory called **aghpb** and where is the main code file with the name **init.lua**

**### Modifications:**
- [x] Modifying the **rockspec** file.
- [x] Following the standards.

Hope to be useful and happy to be involved. Thank you and have good day!
Greetings from **Yassin**.

**Comment by THEGOLDENPRO** [comment]
Weird it was working perfectly before but alright thanks again I will have a look at it.

**Comment by THEGOLDENPRO** [comment]
umm that doesn't seem to be working, I'm getting `Error: Directory 1.2 not found inside archive 1.2.tar.gz` in console when I try and upload.

**Comment by THEGOLDENPRO** [comment]
if I remove that it lets me publish it but we still have the build error, I'm really confused because this was working perfectly fine before the v1.1 pr

**Comment by THEGOLDENPRO** [comment]
and btw it installs perfectly when doing it locally with `luarocks make`

**Comment by achengli** [comment]
Must be the name of the download file in the rockspec, before was for 1.1 release and now must to be for 1.2 then the name of the **url** section in the file must have that terminology.

Now it throws me this error when attempting to install it locally.

> Error: Build error: Failed installing src/aghpb/init.lua in /home/tao/.luarocks/lib/luarocks/rocks-5.3/aghpb/1.2-0/lua/aghpb/init.lua: src/aghpb/init.lua: No such file or directory

**Comment by THEGOLDENPRO** [comment]
ah, I think I found the reasoning behind that

**Comment by THEGOLDENPRO** [comment]
yeah still broken, I give up 😐 for now

**Comment by achengli** [comment]
I was comparing with other lua packages but they did it with the release url.

I will research more tomorrow. Thank you!

**Comment by THEGOLDENPRO** [comment]
> I was comparing with other lua packages but they did it with the release url.
> 
> I will research more tomorrow. Thank you!

nvm I fixed it 🥳
